# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PFXFillGood' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PFXFillGood
  pod 'ProgressHUD'
  pod 'paper-onboarding'
  pod 'Google-Mobile-Ads-SDK'
  pod 'ConcentricOnboarding'
  
  target 'PFXFillGoodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PFXFillGoodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
